name: VIRTUOS INTEGRATION 11

on: 
  push: 
    branches: [main]
  pull_request:
        branches: [main]
  workflow_dispatch:

jobs:
    TestByVrtuoso:
      runs-on: ubuntu-latest
      env:
        SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}

      permissions:
        id-token: write # This is required for requesting the JWT
        contents: read # This is required for actions/checkout
        
        #  code for if condition 
        # if: github.ref == 'refs/heads/main' 
        
      steps:
        - name: Repo Checkout to GitRunner
          uses: actions/checkout@v3 
          
        - name: Initialize Notification By Slack
          if: always()
          run: |
            # Prepare the payload for Slack message
            GITHUB_COMMIT_MESSAGE=$(git log -1 --pretty=%B)
            #SLACK_MESSAGE="*(Virtuoso Msg)* ID: *$GITHUB_RUN_NUMBER* \nDeployment to staging branch was *$GITHUB_EVENT_NAME*.\nDeployment Status: *started*\nCommitted by: *$(git log -1 --pretty=%an)*\nCommit Message: *$GITHUB_COMMIT_MESSAGE*"
             SLACK_MESSAGE="*[$GITHUB_REPOSITORY/${{ github.head_ref || github.ref_name }}/$GITHUB_RUN_NUMBER]*
                            \n*(1) Virtuoso Testing Started..*" 
            SLACK_PAYLOAD="{\"text\": \"$SLACK_MESSAGE\"}"
            # Send the notification to Slack
            curl -X POST -H 'Content-type: application/json' --data "$SLACK_PAYLOAD" $SLACK_WEBHOOK_URL
        
        - name: Connect and Execute the shellscript for Virtuoso
          run: |
            bash virtuoso/goals.sh ${{vars.VIRTUOSO_TOKEN}}

        - name: Notfiy the Virtuoso result 
          if: always()
          run: |
            # Prepare the payload for Slack message
            GITHUB_COMMIT_MESSAGE=$(git log -1 --pretty=%B)
            SLACK_MESSAGE="*(2) Virtuoso Testing Completed* 
                        \n"*(3) Result: ${{ job.status }}*" 
            SLACK_PAYLOAD="{\"text\": \"$SLACK_MESSAGE\"}"
            
            # Send the notification to Slack
            curl -X POST -H 'Content-type: application/json' --data "$SLACK_PAYLOAD" $SLACK_WEBHOOK_URL



          
