name: VIRTUOS INTEGRATION 11

on: 
  push: 
    branches: [main]
  pull_request:
        branches: [main]
  workflow_dispatch:

jobs:
    Initialized:
      runs-on: ubuntu-latest
      steps:
        - name: Echo Message 
          run: |
            echo "welcome"
            

          
