name: VIRTUOS INTEGRATION 1

on: 
  push: 
    branches: [main]
  pull_request:
        branches: [main]
  workflow_dispatch:

jobs:
    open-git-container-terminal:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repo
          uses: actions/checkout@v2
          
        - name: execue virtuoso shell script 1
          run: |
            bash virtuoso/execute.sh -t ${{vars.VIRTUOSO_TOKEN}} --goal_id ${{vars.GOAL_ID}}            

          
