name: VIRTUOS INTEGRATION 

on: 
  push: 
    branches: [main]
  pull_request:
        branches: [main]
  workflow_dispatch:

jobs:
    connect-machine:
      runs-on: ubuntu-latest
      steps:
        - name: echo message 
          run: echo "welcome"
         
  
