name: VIRTUOS INTEGRATION 11

on: 
  push: 
    branches: [main]
  pull_request:
        branches: [main]
  workflow_dispatch:

jobs:
    ExecuteShellScrpt:
      runs-on: ubuntu-latest
      steps:
        - name: Gheckout to Git Runner
        - uses: actions/checkout@v2 


          
