name: VIRTUOS INTEGRATION 

on: 
  push: 
    branches: [main]
  pull_request:
        branches: [main]
  workflow_dispatch:

jobs:
    open-git-container:
      runs-on: ubuntu-latest
      steps:
        - name: echo message 
          run: ls -la
          
  
