name: VIRTUOS INTEGRATION 1

on: 
  push: 
    branches: [main]
  pull_request:
        branches: [main]
  workflow_dispatch:

jobs:
    Initialized:
      runs-on: ubuntu-latest
      steps:
        - name: Echo Message 
          run: |
            echo "welcome"
            
    ExecuteShellScript:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout Repo to Git Runner
      - uses: actions/checkout@v2        
     
      - name: execue virtuoso shell script 1
        run: |
            bash virtuoso/goals.sh ${{vars.VIRTUOSO_TOKEN}}           

          
