name: VIRTUOS INTEGRATION 

on: 
  push: 
    branches: [main]
  pull_request:
        branches: [main]
  workflow_dispatch:

jobs:
    open-git-container-terminal:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repo
          uses: actions/checkout@v2
          
        - name: execute  Virtuoso Shell script file  
          run: set VIRTUOSO_TOKEN=${{vars.VIRTUOSO_TOKEN}}
          
        - name: result
          run: echo $VIRTUOSO_TOKEN
          
